services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Amdeu\LabelEditor\:
    resource: '../Classes/*'

  Amdeu\LabelEditor\Backend\Controller\LabelEditorController:
    public: true