services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  UBOS\LabelEditor\:
    resource: '../Classes/*'

  UBOS\LabelEditor\Backend\Controller\LabelEditorController:
    public: true